name: swiftlint

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  swiftlint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ghcr.io/realm/swiftlint:0.63.2
    steps:
      - uses: actions/checkout@v7
      - name: swiftlint
        run: swiftlint --reporter github-actions-logging --strict
